### ISSUE TITLE
Not able to set font between 1 and 2

### ISSUE THREAD

**Issue by NagendraSV** [adafruit/Adafruit-GFX-Library#120]
Hi,
I am using Adafruit_GFX libraries in Arduino and i am able to display fonts on the OLED.
I feel the setTextSize of 2 is too big and setTextSize of 1 is small. If i change the uint8_t to float and if i set the setTextSize to 1.5, the code doesnt work and it still takes the font size of 1.
Can anybody help me in order to set the setTextSize to 1.5 or 1.75?

regards,
Nagendra

**Comment by PaintYourDragon** [comment]
The font renderer only handles integer scales. If you need an in-between size, use the setFont() function with corresponding font header file; there's a bunch included with the library, or with some extra work you may be able to generate your own custom exact sizes. It's documented here:

https://learn.adafruit.com/adafruit-gfx-graphics-library/using-fonts
