### ISSUE TITLE
v1.2.3 breaks platformio build, because dependency to SPI is missing.

### ISSUE THREAD

**Issue by euphi** [adafruit/Adafruit-GFX-Library#146]
See https://travis-ci.org/euphi/ESP-Touch/builds/325626440 for example - this build failed after update to 1.2.3

Since some time(?) platformio needs internal libs as dependency. So, the issue is solved by added a SPI to library.properties

**Comment by 5shekel** [comment]
thank you for the workaround @euphi  

can you explain how to add spi to library.properties

**Comment by 5shekel** [comment]
see https://github.com/platformio/platformio-libmirror/issues/91#issuecomment-244614304

i added 
 `#include <SPI.h> `

**Comment by ladyada** [comment]
hiya please submit a PR :)

**Comment by 5shekel** [comment]
prefer not to PR, i dont know where it's best to add that line. i added it to my src code.

thanks for the lib!
