### ISSUE TITLE
ESP32 Wifi not connect

### ISSUE THREAD

**Issue by T365** [adafruit/Adafruit-GFX-Library#151]
Arduino-1.8.2 / ESP32
I updated my "May 2017" version with this version, and now wifi will not connect anymore.
I returned back to 06-2017 version...

**Comment by pljakobs** [comment]
Can you provide some minimal test code that shows the issue?

**Comment by x4m3** [comment]
i have an esp32, and im pulling the library straight from git, and wifi works.....

besides, how can this library impact the wifi of the board?

**Comment by pljakobs** [comment]
@ladyada this, too

**Comment by ladyada** [comment]
l8r alg8r :)
