### ISSUE TITLE
Have print() clear existing text

### ISSUE THREAD

**Issue by cacycleworks** [adafruit/Adafruit-GFX-Library#16]
While I was writing the code for my display as it monitors a measurement bench, I learned I needed to manually blank the existing text in a given location. I made a function in my program for this which would fillRect() in the area the text needs to go. In order to do this, I could pass to it the X,Y, but then I have to maintain the cursor coordinates. The Adafruit_GFX class already does this so I added int16_t Adafruit_GFX::getCursor(boolean x) just beneath setCursor(). It returns cursor_x if x is 1 or cursor_y if it isn't. 

Very simple:
int16_t Adafruit_GFX::getCursor(boolean x) {
  if( x )
    return cursor_x;
  return cursor_y;
}

That or expand print() to include an option for clearing the space where it's about to print?

**Comment by lfg6000** [comment]
// this will correctly overwrite 4 digits to the screen

char vBuf[5] = {};

//this is red text on a black background
//setting the background overwrites the previous characters
tft.setTextColor(ST7735_RED, ST7735_BLACK);

// write the 4 digits of the a/d value into a buffer
snprintf(vBuf, sizeof(vBuf)-1, "%4d", potInV);

// location of text to print
tft.setCursor(0, 50);

// output text to display
tft.println(vBuf);

**Comment by avandalen** [comment]
I have made a library extension by wich we can overwrite text and numbers correctly:
[https://www.avdweb.nl/arduino/hardware-interfacing/ili9341-tft]
See GitHub:
[https://github.com/avandalen/ILI9341-overwrite-text](url)

**Comment by eudoxos** [comment]
(FWIW links in the last comment do not point where they should)

**Comment by avandalen** [comment]
Is solved

**Comment by DJDevon3** [comment]
I'm using the HX8357 3.5" TFT which looks pretty good with a 320x480 wallpaper. Text background color is a nice work around for a solid color screen but if you load a bmp wallpaper as a TFT background image this workaround isn't sufficient.  A "clear" or "blank" background color would be ideal.  If you can refresh characters with a background color then why not make a clear one?

**Comment by avandalen** [comment]
Yes good idea,
but I have no time, maybe you can get someone who can add this to github.
you can add this to github issues..

kind regards

Albert
