### ISSUE TITLE
Faster refresh rate using SPI DMA

### ISSUE THREAD

**Issue by davidperrenoud** [adafruit/Adafruit-GFX-Library#170]
As you are [making a game console](https://blog.adafruit.com/2018/05/25/we-are-making-a-circuitpython-based-gaming-platform-adafruit/), have you planned on adding support for SPI DMA in order to have a faster refresh rate on the ATSAMD21 and ATSAMD51?

Related: https://github.com/adafruit/Adafruit-ST7735-Library/issues/43

**Comment by ladyada** [comment]
https://github.com/adafruit/Adafruit-GFX-Library/tree/samd-dma

**Comment by davidperrenoud** [comment]
@PaintYourDragon Could you briefly tell what the state of this DMA branch is?

**Comment by ladyada** [comment]
unfinished! when its ready we'll merge into master :)
