### ISSUE TITLE
please provide examples for create button and detect  button press

### ISSUE THREAD

**Issue by dsyleixa** [adafruit/Adafruit-GFX-Library#179]
please provide examples for create button and detect  button press
(Featherwing 3.5", Feather Huzzah, <Adafruit_STMPE610.h> , <Adafruit_HX8357.h>),
a) landscape
b) portrait

**Comment by ladyada** [comment]
because you opened it in another location

**Comment by dsyleixa** [comment]
I wasn't sure if it's for a Display driver example or for a GFX example - which would be the correct place?

**Comment by ladyada** [comment]
its fine, please don't keep bumping issues
