### ISSUE TITLE
I got this as an error message when trying to upload a blink program to Hallowing.  I have followed other things to try to correct it even deleting all libraries and starting over.  Anyone have any ideas how to fix this?

### ISSUE THREAD

**Issue by Larkenware** [adafruit/Adafruit-GFX-Library#184]
Arduino: 1.8.7 (Mac OS X), TD: 1.44, Board: "Adafruit Hallowing M0"

In file included from /Users/larkenware/Library/Arduino15/packages/arduino/tools/CMSIS-Atmel/1.2.0/CMSIS/Device/ATMEL/samd21/include/samd21.h:69:0,
                 from /Users/larkenware/Library/Arduino15/packages/arduino/tools/CMSIS-Atmel/1.2.0/CMSIS/Device/ATMEL/samd.h:105,
                 from /Users/larkenware/Library/Arduino15/packages/arduino/tools/CMSIS-Atmel/1.2.0/CMSIS/Device/ATMEL/sam.h:540,
                 from /Users/larkenware/Library/Arduino15/packages/adafruit/hardware/samd/1.2.3/cores/arduino/Arduino.h:48,
                 from sketch/Blink.ino.cpp:1:
/Users/larkenware/Library/Arduino15/packages/arduino/tools/CMSIS-Atmel/1.2.0/CMSIS/Device/ATMEL/samd21/include/samd21g18a.h:237:26: fatal error: core_cm0plus.h: No such file or directory
 #include <core_cm0plus.h>
                          ^
compilation terminated.
exit status 1
Error compiling for board Adafruit Hallowing M0.

This report would have more information with
"Show verbose output during compilation"
option enabled in File -> Preferences.

**Comment by ladyada** [comment]
hiya, ditto!
