### ISSUE TITLE
RGB drawBitmap with Mask not working

### ISSUE THREAD

**Issue by tpitman** [adafruit/Adafruit-GFX-Library#187]
I am using the GFX library on a huzzah32. I have converted the image from a bmp using gimp. I also created the 1 bit mask and exported using the glib export plugin for gimp.

The data seems fine in the .h files I ended up with. The image itself draws fine if I use the drawBitmap that doesn't include the mask.

When I try to include the mask I get were results.

I am drawing the same image twice offset a little to see if the masking would work, so having 2 is not the problem. That is on purpose.

Here is what it looks like:
￼
![image](https://user-images.githubusercontent.com/2906563/48822590-d13a6d80-ed1a-11e8-9e95-0265820a3e32.png)

My image data looks like this (cut off for pasting here):

`
/* GIMP RGB C-Source image dump (cup1.c) */

static const struct {
  unsigned int 	 width;
  unsigned int 	 height;
  unsigned int 	 bytes_per_pixel; /* 2:RGB16, 3:RGB, 4:RGBA */ 
  unsigned char	 pixel_data[100 * 95 * 2 + 1];
} gimp_image PROGMEM = {
  100, 95, 2,
  "\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\000\000\000\000"
  "\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000"
  "\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000"
`

When I call the drawBitmap I just have to cast the pixel_data to (unsigned short*) and that works fine.

Here is what my mask data looks like (cut off for pasting here):
`unsigned char cup1_mask_bits[] PROGMEM = {
  0xFC, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF,
  0xE3, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF,
`

Here is what my calls to drawBitmap look like:

`
tft.drawRGBBitmap(0, 0, (unsigned short*)gimp_image.pixel_data, cup1_mask_bits, gimp_image.width, gimp_image.height);

  tft.drawRGBBitmap(30, 30, (unsigned short*)gimp_image.pixel_data, cup1_mask_bits, gimp_image.width, gimp_image.height);
`

**Comment by PaintYourDragon** [comment]
I'm not familiar with the glib export plugin, but see if it has an option to pad scanlines to the next byte boundary. GFX requires this. If the option isn't there, round up the image width to the next multiple of 8 (e.g. 104 pixels), with the extra pixels on the right. This is only needed for the bitmask...the RGB image, being 16-bit, is already aligned at each scanline.

**Comment by tpitman** [comment]
That makes sense. Thanks.
