### ISSUE TITLE
fillRoundRect error with small width

### ISSUE THREAD

**Issue by joshuajayg** [adafruit/Adafruit-GFX-Library#188]
When drawing a round rectangle with less than twice the radius, the sketch crashes.  

example: 
tft.fillRoundRect(10, 10, 3, 10, 2, ILI9341_WHITE);

With a width of 3 and radius of 2, the library cannot gracefully handle the error.  Obviously I can add an if statement to handle this but it seems as though the library should be able to gracefully handle this problem by making a squared off rectangle.

**Comment by PaintYourDragon** [comment]
Fixed in 1.3.4. Thanks for spotting this!
