### ISSUE TITLE
compile error in version 1.3.6

### ISSUE THREAD

**Issue by clear-sky** [adafruit/Adafruit-GFX-Library#193]
trying to compile fontconver but see this error
gcc -Wall -I/usr/local/include/freetype2 -I/usr/include/freetype2 -I/usr/include fontconvert.c -lfreetype -o fontconvert
fontconvert.c: In function 'main':
fontconvert.c:125:32: error: 'TT_INTERPRETER_VERSION_35' undeclared (first use in this function)
  FT_UInt interpreter_version = TT_INTERPRETER_VERSION_35;
                                ^~~~~~~~~~~~~~~~~~~~~~~~~
fontconvert.c:125:32: note: each undeclared identifier is reported only once for each function it appears in
fontconvert.c:126:2: warning: implicit declaration of function 'FT_Property_Set'; did you mean 'FT_Face_Properties'? [-Wimplicit-function-declaration]
  FT_Property_Set( library, "truetype",
  ^~~~~~~~~~~~~~~
  FT_Face_Properties
make: *** [Makefile:8: fontconvert] Error 1

**Comment by cmdrf** [comment]
I also ran into this issue on Debian 9 (FreeType 2.6.3).

Adding `#include FT_TRUETYPE_DRIVER_H` to the list of includes seems to fix the issue.

**Comment by ladyada** [comment]
hiya folks, could you submit a PR?

**Comment by varna9000** [comment]
Adding these two lines to the header, clears the error (testes on Mac OS X):

#include FT_MODULE_H
#define TT_INTERPRETER_VERSION_35  35

**Comment by ladyada** [comment]
:)
