### ISSUE TITLE
Possible issue with rotation.

### ISSUE THREAD

**Issue by caternuson** [adafruit/Adafruit-GFX-Library#208]
See here:
https://forums.adafruit.com/viewtopic.php?f=19&t=149836

Uncanny Eye related. Image offset with some rotation values.

**Comment by ladyada** [comment]
this is low priority, Uncanny Eye is very optimized and not designed for 90* rotations

**Comment by caternuson** [comment]
Thanks. Doesn't really sound like a GFX issue then. Guess we can close this?
