### ISSUE TITLE
sercom SPI is not working

### ISSUE THREAD

**Issue by orhanyor** [adafruit/Adafruit-GFX-Library#215]
hello i just opened an issue in st7735 page but since it concerns gfx library too i needed to let you know that it is not working. original implementation of @daniel-stewart still works but i guess something broke along the way in the futher releases. here is the link for more information. 

https://github.com/adafruit/Adafruit-ST7735-Library/issues/70

**Comment by PaintYourDragon** [comment]
Fixed in Adafruit_GFX version 1.4.12. Thanks for finding this!

**Comment by orhanyor** [comment]
thank you
