### ISSUE TITLE
Adafruit gfx Raspberry Pi WiringPi

### ISSUE THREAD

**Issue by Flo082002** [adafruit/Adafruit-GFX-Library#229]
Is there a way to use Adafruit Gfx with wiringPi on a Raspberry Pi?

**Comment by makermelissa** [comment]
I don’t believe so. This was designed for use on arduinos, so it would most likely require a lot of changes.

**Comment by makermelissa** [comment]
As an aside, if you’re interested in Python, you could probably get adafruit-blinka working with the adafruit-circuitpython-rgb-display library. You can learn more here: https://learn.adafruit.com/circuitpython-on-raspberrypi-linux.
