### ISSUE TITLE
Creating a custom backend for a custom display

### ISSUE THREAD

**Issue by willfurnell** [adafruit/Adafruit-GFX-Library#233]
Hi,
I've got a custom display (84x8 flipdot) and was thinking of making a backend for it so I can use this library to write to it easily. Is there some documenation/really simple examples/etc. on creating a custom backend? Are backends _required_ to be SPI displays?

Thank you!

**Comment by ladyada** [comment]
nope, anything that implements setPixel can be used. we have i2c displays and ones that have an intermediate chip.
here's some simple implementations
https://github.com/adafruit/Adafruit_SHARP_Memory_Display
https://github.com/adafruit/Adafruit_LED_Backpack
good luck :)

**Comment by willfurnell** [comment]
Thank you!
