### ISSUE TITLE
Adafruit_SPITFT fails on Xmega or AVR8X targets e.g. ATmega4809

### ISSUE THREAD

**Issue by prenticedavid** [adafruit/Adafruit-GFX-Library#234]
Many third party libraries inherit Adafruit_GFX and the world is very grateful for Adafruit's work.

Adafruit_SPITFT introduced a "risky" typedef name for accessing Ports.
PORT_t is used by Xmega and AVR8X headers.

It appears that `PORT_t` is only used by Adafruit_SPITFT files.     I suggest that `RWREG_t` might be a safer name.    Or simply call it `ADA_PORT_t`

Likewise,   the SPI registers have different names on Xmega and AVR8X chips.
So all the SPDR code needs an extra conditional block.   e.g.

```
 #if defined(__AVR_ATmega4809__)
            for(SPI0_DATA = hi; !(SPI0_INTFLAGS & _BV(SPI_IF_bp)); );
            for(SPI0_DATA = lo; !(SPI0_INTFLAGS & _BV(SPI_IF_bp)); );
 #elif defined(__AVR__)
            for(SPDR = hi; !(SPSR & _BV(SPIF)); );
            for(SPDR = lo; !(SPSR & _BV(SPIF)); );
 #elif defined(ESP32)
           ...

```

Life would be simpler if you just have one conditional macro for AVR_SPI_WRITE()
Then you don't have multiple occurrences to maintain.

Yes,   I would be happier with testing a generic macro e.g. `__AVR_ENHANCED__` instead of  `__AVR_ATmega4809__`

David.

**Comment by ladyada** [comment]
we don't have any xmega or 4809's but we're happy to take a PR!

**Comment by prenticedavid** [comment]
I posted as an "Issue" because I wanted an opinion about a suitable typedef name and an opinion about a single AVR_SPI_WRITE() macro (and a suitable name).

I will Fork later and offer a Pull Request.

David.

**Comment by ladyada** [comment]
sure, you can change the name to `ADAGFX_PORT_t` that way there's no conflict

**Comment by WillEccles** [comment]
Ran into this same issue today. The Nano Every won't support this library until this is fixed. I'm almost certainly going to fix it myself tonight and would be happy to PR if @prenticedavid doesn't want to/doesn't have the time to.

**Comment by prenticedavid** [comment]
I have already submitted a Pull Request.
My apologies for not updating the "Issues"

@WillEccles,
Please try the PR for yourself.    Can you suggest "better" names?
Is there a more appropriate predefined macro to distinguish AVR8X from XMEGA ?

David.

**Comment by WillEccles** [comment]
@prenticedavid I already have implemented your fork in my own project. Before I realized you had already done it, I started doing it myself, and `ADAGFX_PORT_t` is the exact typename I chose myself. I think it's about the best option available, unless you used a namespace around `PORT_t`, which I think is far from optimal in this situation.

As for the macro, I have no suggestions one way or another, I think you did a fine job. Thanks for fixing it for all of us!

**Comment by WillEccles** [comment]
By the way, I am not sure if you know this, but on GitHub, if you reference the issue number and say something like `fixes #234` in the PR, GitHub will update the referenced issue(s) and automatically close the issue when the PR is merged. I explicitly mentioned the PR number in my previous message so that there was a link from one to the other and back again for future readers.

Of course, if you already knew that, then carry on!

**Comment by prenticedavid** [comment]
Thanks for the tip.   I did not know about the Issue#

**Comment by ladyada** [comment]
ok this should be all good now, - please try the new release!
