### ISSUE TITLE
Off-screen drawing and saving?

### ISSUE THREAD

**Issue by Sortland** [adafruit/Adafruit-GFX-Library#261]
I'm basically looking for some drawing functions to create an image where no display is involved (the image is intended to be transferred via a webserver running on my board).

So my question: is the Ada-GFX-lib able to use a drawing buffer of a given size without any hardware involved, draw some things on that buffer and then provide the resulting image data for further processing?

Thanks!

**Comment by mzero** [comment]
It already does this. See the classes `GFXcanvas1`, `GFXcanvas8`, and `GFXcanvas16` at the end of `Adafruit_GFX.h`
