### ISSUE TITLE
Font dimensions

### ISSUE THREAD

**Issue by aliktab** [adafruit/Adafruit-GFX-Library#27]
Please make functions for current font char dimensions (char width and height for currently selected font and it's size).
Also be good to have width and height functions for string.

**Comment by jayeye** [comment]
(a bit too late to answer, but you you can get those by iterating through the font definition).

**Comment by aliktab** [comment]
I can, of course, but we have there a mini controller with small amount of memory and a quite slow. A you really think it's good solution to make such functions?

In any case it's good for such class to have those functions I think. I can make them on my own of course.

**Comment by tablatronix** [comment]
some abstractions here would also be nice so making functions like `setLine()` are doable.
`getTextBounds` seems like it might solve for post, but is overkill for this `gettextsize` helper maybe?

```
  display.setTextSize(2);
  display.setCursor(0,(display.getTextSize()*lineheight) * line);
```
