### ISSUE TITLE
compile error with freetype version 2.10.1

### ISSUE THREAD

**Issue by athusrv** [adafruit/Adafruit-GFX-Library#273]
trying to compile fontconvert but see this error:
warning: implicit declaration of function 'FT_Property_Set'; did you mean 'FT_Face_Properties'? [-Wimplicit-function-declaration]
   FT_Property_Set(library, "truetype", "interpreter-version",
   ^~~~~~~~~~~~~~~
   FT_Face_Properties

Looks like the version 2.10.1 (probably 2.10.0 too) expect the fontconvert.c to include these headers as laided out [here](https://github.com/servo/libfreetype2/blob/master/freetype2/docs/CHANGES#L752)

#include FT_MODULE_H
#include FT_CFF_DRIVER_H

After including these headers, the fontconverter was compiled successfully.

**Comment by ladyada** [comment]
hihi please submit a PR :)

**Comment by BillyDonahue** [comment]
fixed now. The comment on #297 didn't use the right magic words to autoclose this on merge.

**Comment by ladyada** [comment]
rad :)
