### ISSUE TITLE
Error compiling for arduino mega 2560

### ISSUE THREAD

**Issue by KanjiMaster** [adafruit/Adafruit-GFX-Library#335]
I connected the MCUfriend LCD display to my arduino mega 2560 it lights up and all but when i try to upload the canvas example it gives me this error:

In file included from C:\Users\KanjiMaster\Documents\Arduino\libraries\Adafruit-GFX-Library-master\Adafruit_GrayOLED.cpp:20:0:
C:\Users\KanjiMaster\Documents\Arduino\libraries\Adafruit-GFX-Library-master\Adafruit_GrayOLED.h:30:10: fatal error: Adafruit_I2CDevice.h: No such file or directory
 #include <Adafruit_I2CDevice.h>
          ^~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
exit status 1
Error compiling for board Arduino Mega or Mega 2560.

Any help would be very appreciated!

**Comment by ladyada** [comment]
https://github.com/adafruit/Adafruit-GFX-Library/blob/master/library.properties#L10
