### ISSUE TITLE
Add support for second hw SPI

### ISSUE THREAD

**Issue by maxholgasson** [adafruit/Adafruit-GFX-Library#361]
Hi, is it possible to add a second hardware SPI to the GFX library besides of the default SPI?

**Comment by kmsmi** [comment]
I join the question. Is it possible to use a second SPI?

**Comment by ladyada** [comment]
pass in SPIclass here
https://github.com/adafruit/Adafruit-GFX-Library/blob/master/Adafruit_SPITFT.h#L145

**Comment by kmsmi** [comment]
Thanks.
