### ISSUE TITLE
Add fast text drawing API

### ISSUE THREAD

**Issue by bitbank2** [adafruit/Adafruit-GFX-Library#382]
The GFX library is mostly based on drawing single pixels at a time to draw larger items. It allows simpler compatibility across different device types, but negatively affects performance. Would Adafruit accept a new set of functions for quickly drawing text? Faster text drawing would allow for some new use cases on serial displays such as demonstrated below. This demo is a file explorer which redraws the entire display to scroll/update the text.

https://youtu.be/SSrdWZNyAhI

The code uses the Adafruit_GFX/TFT API and is quite simple in the way that it optimizes text drawing. Let me know if you would accept the new feature and I'll create a pull request.

**Comment by ladyada** [comment]
hiya sounds good on submitting a PR - as long as it doesn't break existing examples/functionality!  lots of people are using this library so we are careful not to make things stop working.
