### ISSUE TITLE
Fix the PlatformIO dependencies

### ISSUE THREAD

**Issue by alba-ado** [adafruit/Adafruit-GFX-Library#388]
Can you please solve this issue which is mentioned in the PlatformIO community;

https://community.platformio.org/t/adafruit-gfx-lib-will-not-build-any-more-pio-5/15776/13

They say that it is caused by not including the <Adafruit_I2CDevice.h> in the header files. So it should be a relatively easy fix.

**Comment by ladyada** [comment]
please submit a PR, it should pass CI and we can merge it!

**Comment by alba-ado** [comment]
Created a pull request in #389

**Comment by alba-ado** [comment]
Issue resolved in #389
