### ISSUE TITLE
Should cursor_x and cursor_y be public?

### ISSUE THREAD

**Issue by holymoly** [adafruit/Adafruit-GFX-Library#44]
Hi,
Im using the library together with the 0.96" 16-bit Color OLED with the SSD1331 driver chip. I looked for a way to get the current cursor position and couldn't find one. So should these two be public or should there be a get Method?
Or am I missing something?

**Comment by Mokolea** [comment]
I also had to use the current cursor position. So I suggested to implement get-methods, see pull request #45

**Comment by PaintYourDragon** [comment]
Recently merged. Thank you for contributing!
