### ISSUE TITLE
Font size description in glcdfont.c file is incorrect

### ISSUE THREAD

**Issue by azirger** [adafruit/Adafruit-GFX-Library#61]
glcdfont.c claims the described font is 5x7.  Looking at the bitmaps, it is 5x8.  There are used pixels on both the top and bottom rows, so the full byte width is used at different times.

You can easily tell by looking for any bytes with size >= 80h (msb used) and bytes that are odd (lsb used).

**Comment by PaintYourDragon** [comment]
Semantics. Baseline to cap height is 7 pixels. But yes, a few symbols and some lower-case letters may have descenders using the 8th bit.
