### ISSUE TITLE
Example code for fonts

### ISSUE THREAD

**Issue by Bodmer** [adafruit/Adafruit-GFX-Library#67]
I can't find any examples, attached may be of interest.
[Any_GFX_Font.zip](https://github.com/adafruit/Adafruit-GFX-Library/files/76114/Any_GFX_Font.zip)

**Comment by Bodmer** [comment]
Closed due to lack of interest.

**Comment by pljakobs** [comment]
@Bodmer, you have made some good suggestions, but as long as you don't create a pull request, chances are noone will pick up the integration work.
If you have a working implementation of your code in your own fork, see if it merges with the current master and create a PR.
