### ISSUE TITLE
getTextBounds returns no width

### ISSUE THREAD

**Issue by realbuxtehuder** [adafruit/Adafruit-GFX-Library#81]
For default font:
If no text wrap occurrs, then only `lineWith` is incremented by `textsize * 6`. 
But when the string ends, `*w` is returned with `maxWith -1`, which is still at the initial 0.

**Comment by realbuxtehuder** [comment]
Just found the pull request #71 from markwal which would solve exact this issue.
Please merge his request.

**Comment by SaschaZorn** [comment]
Just ran into the same bug and fixed it the same way! Please merge this ASAP!

**Comment by markwal** [comment]
@PaintYourDragon

**Comment by atheros** [comment]
Please merge #71 to fix this very annoying bug

**Comment by PaintYourDragon** [comment]
Merged, fixed, thanks folks.
