### ISSUE TITLE
Hey, i have an arduino 101 and iam trying to run it with the adafruit st7735 tft and iam getting some errors while compiling

### ISSUE THREAD

**Issue by tanann** [adafruit/Adafruit-GFX-Library#98]

**Comment by tanann** [comment]
Arduino: 1.6.12 (Windows 10), Board: "Arduino/Genuino 101"

C:\Users\tanma\OneDrive\Documents\Arduino\libraries\Adafruit-ST7735-Library-master\Adafruit_ST7735.cpp: In constructor 'Adafruit_ST7735::Adafruit_ST7735(int8_t, int8_t, int8_t, int8_t, int8_t)':

C:\Users\tanma\OneDrive\Documents\Arduino\libraries\Adafruit-ST7735-Library-master\Adafruit_ST7735.cpp:47:3: error: '_cs' was not declared in this scope

   _cs   = cs;

   ^

C:\Users\tanma\OneDrive\Documents\Arduino\libraries\Adafruit-ST7735-Library-master\Adafruit_ST7735.cpp:48:3: error: '_rs' was not declared in this scope

   _rs   = rs;

   ^

C:\Users\tanma\OneDrive\Documents\Arduino\libraries\Adafruit-ST7735-Library-master\Adafruit_ST7735.cpp:49:3: error: '_sid' was not declared in this scope

   _sid  = sid;

   ^

C:\Users\tanma\OneDrive\Documents\Arduino\libraries\Adafruit-ST7735-Library-master\Adafruit_ST7735.cpp:50:3: error: '_sclk' was not declared in this scope

   _sclk = sclk;

   ^

C:\Users\tanma\OneDrive\Documents\Arduino\libraries\Adafruit-ST7735-Library-master\Adafruit_ST7735.cpp:51:3: error: '_rst' was not declared in this scope

   _rst  = rst;

   ^

C:\Users\tanma\OneDrive\Documents\Arduino\libraries\Adafruit-ST7735-Library-master\Adafruit_ST7735.cpp: In constructor 'Adafruit_ST7735::Adafruit_ST7735(int8_t, int8_t, int8_t)':

C:\Users\tanma\OneDrive\Documents\Arduino\libraries\Adafruit-ST7735-Library-master\Adafruit_ST7735.cpp:60:3: error: '_cs' was not declared in this scope

   _cs   = cs;

   ^

C:\Users\tanma\OneDrive\Documents\Arduino\libraries\Adafruit-ST7735-Library-master\Adafruit_ST7735.cpp:61:3: error: '_rs' was not declared in this scope

   _rs   = rs;

   ^

C:\Users\tanma\OneDrive\Documents\Arduino\libraries\Adafruit-ST7735-Library-master\Adafruit_ST7735.cpp:62:3: error: '_rst' was not declared in this scope

   _rst  = rst;

   ^

C:\Users\tanma\OneDrive\Documents\Arduino\libraries\Adafruit-ST7735-Library-master\Adafruit_ST7735.cpp:64:3: error: '_sid' was not declared in this scope

   _sid  = _sclk = 0;

   ^

C:\Users\tanma\OneDrive\Documents\Arduino\libraries\Adafruit-ST7735-Library-master\Adafruit_ST7735.cpp:64:11: error: '_sclk' was not declared in this scope

   _sid  = _sclk = 0;

           ^

C:\Users\tanma\OneDrive\Documents\Arduino\libraries\Adafruit-ST7735-Library-master\Adafruit_ST7735.cpp: In member function 'void Adafruit_ST7735::spiwrite(uint8_t)':

C:\Users\tanma\OneDrive\Documents\Arduino\libraries\Adafruit-ST7735-Library-master\Adafruit_ST7735.cpp:93:20: error: 'dataport' was not declared in this scope

       if(c & bit) *dataport |=  datapinmask;

                    ^

C:\Users\tanma\OneDrive\Documents\Arduino\libraries\Adafruit-ST7735-Library-master\Adafruit_ST7735.cpp:93:33: error: 'datapinmask' was not declared in this scope

       if(c & bit) *dataport |=  datapinmask;

                                 ^

C:\Users\tanma\OneDrive\Documents\Arduino\libraries\Adafruit-ST7735-Library-master\Adafruit_ST7735.cpp:94:20: error: 'dataport' was not declared in this scope

       else        *dataport &= ~datapinmask;

                    ^

C:\Users\tanma\OneDrive\Documents\Arduino\libraries\Adafruit-ST7735-Library-master\Adafruit_ST7735.cpp:94:33: error: 'datapinmask' was not declared in this scope

       else        *dataport &= ~datapinmask;

                                 ^

C:\Users\tanma\OneDrive\Documents\Arduino\libraries\Adafruit-ST7735-Library-master\Adafruit_ST7735.cpp:95:8: error: 'clkport' was not declared in this scope

       *clkport |=  clkpinmask;

        ^

C:\Users\tanma\OneDrive\Documents\Arduino\libraries\Adafruit-ST7735-Library-master\Adafruit_ST7735.cpp:95:20: error: 'clkpinmask' was not declared in this scope

       *clkport |=  clkpinmask;

                    ^

C:\Users\tanma\OneDrive\Documents\Arduino\libraries\Adafruit-ST7735-Library-master\Adafruit_ST7735.cpp: In member function 'void Adafruit_ST7735::writecommand(uint8_t)':

C:\Users\tanma\OneDrive\Documents\Arduino\libraries\Adafruit-ST7735-Library-master\Adafruit_ST7735.cpp:106:4: error: 'rsport' was not declared in this scope

   *rsport &= ~rspinmask;

    ^

C:\Users\tanma\OneDrive\Documents\Arduino\libraries\Adafruit-ST7735-Library-master\Adafruit_ST7735.cpp:106:15: error: 'rspinmask' was not declared in this scope

   *rsport &= ~rspinmask;

               ^

C:\Users\tanma\OneDrive\Documents\Arduino\libraries\Adafruit-ST7735-Library-master\Adafruit_ST7735.cpp:107:4: error: 'csport' was not declared in this scope

   *csport &= ~cspinmask;

    ^

C:\Users\tanma\OneDrive\Documents\Arduino\libraries\Adafruit-ST7735-Library-master\Adafruit_ST7735.cpp:107:15: error: 'cspinmask' was not declared in this scope

   *csport &= ~cspinmask;

               ^

C:\Users\tanma\OneDrive\Documents\Arduino\libraries\Adafruit-ST7735-Library-master\Adafruit_ST7735.cpp: In member function 'void Adafruit_ST7735::writedata(uint8_t)':

C:\Users\tanma\OneDrive\Documents\Arduino\libraries\Adafruit-ST7735-Library-master\Adafruit_ST7735.cpp:123:4: error: 'rsport' was not declared in this scope

   *rsport |=  rspinmask;

    ^

C:\Users\tanma\OneDrive\Documents\Arduino\libraries\Adafruit-ST7735-Library-master\Adafruit_ST7735.cpp:123:15: error: 'rspinmask' was not declared in this scope

   *rsport |=  rspinmask;

               ^

C:\Users\tanma\OneDrive\Documents\Arduino\libraries\Adafruit-ST7735-Library-master\Adafruit_ST7735.cpp:124:4: error: 'csport' was not declared in this scope

   *csport &= ~cspinmask;

    ^

C:\Users\tanma\OneDrive\Documents\Arduino\libraries\Adafruit-ST7735-Library-master\Adafruit_ST7735.cpp:124:15: error: 'cspinmask' was not declared in this scope

   *csport &= ~cspinmask;

               ^

C:\Users\tanma\OneDrive\Documents\Arduino\libraries\Adafruit-ST7735-Library-master\Adafruit_ST7735.cpp: In member function 'void Adafruit_ST7735::commonInit(const uint8_t*)':

C:\Users\tanma\OneDrive\Documents\Arduino\libraries\Adafruit-ST7735-Library-master\Adafruit_ST7735.cpp:310:3: error: 'colstart' was not declared in this scope

   colstart  = rowstart = 0; // May be overridden in init func

   ^

C:\Users\tanma\OneDrive\Documents\Arduino\libraries\Adafruit-ST7735-Library-master\Adafruit_ST7735.cpp:310:15: error: 'rowstart' was not declared in this scope

   colstart  = rowstart = 0; // May be overridden in init func

               ^

C:\Users\tanma\OneDrive\Documents\Arduino\libraries\Adafruit-ST7735-Library-master\Adafruit_ST7735.cpp:312:11: error: '_rs' was not declared in this scope

   pinMode(_rs, OUTPUT);

           ^

C:\Users\tanma\OneDrive\Documents\Arduino\libraries\Adafruit-ST7735-Library-master\Adafruit_ST7735.cpp:313:11: error: '_cs' was not declared in this scope

   pinMode(_cs, OUTPUT);

           ^

C:\Users\tanma\OneDrive\Documents\Arduino\libraries\Adafruit-ST7735-Library-master\Adafruit_ST7735.cpp:314:3: error: 'csport' was not declared in this scope

   csport    = portOutputRegister(digitalPinToPort(_cs));

   ^

C:\Users\tanma\OneDrive\Documents\Arduino\libraries\Adafruit-ST7735-Library-master\Adafruit_ST7735.cpp:315:3: error: 'rsport' was not declared in this scope

   rsport    = portOutputRegister(digitalPinToPort(_rs));

   ^

C:\Users\tanma\OneDrive\Documents\Arduino\libraries\Adafruit-ST7735-Library-master\Adafruit_ST7735.cpp:316:3: error: 'cspinmask' was not declared in this scope

   cspinmask = digitalPinToBitMask(_cs);

   ^

C:\Users\tanma\OneDrive\Documents\Arduino\libraries\Adafruit-ST7735-Library-master\Adafruit_ST7735.cpp:317:3: error: 'rspinmask' was not declared in this scope

   rspinmask = digitalPinToBitMask(_rs);

   ^

C:\Users\tanma\OneDrive\Documents\Arduino\libraries\Adafruit-ST7735-Library-master\Adafruit_ST7735.cpp:337:13: error: '_sclk' was not declared in this scope

     pinMode(_sclk, OUTPUT);

             ^

C:\Users\tanma\OneDrive\Documents\Arduino\libraries\Adafruit-ST7735-Library-master\Adafruit_ST7735.cpp:338:13: error: '_sid' was not declared in this scope

     pinMode(_sid , OUTPUT);

             ^

C:\Users\tanma\OneDrive\Documents\Arduino\libraries\Adafruit-ST7735-Library-master\Adafruit_ST7735.cpp:339:5: error: 'clkport' was not declared in this scope

     clkport     = portOutputRegister(digitalPinToPort(_sclk));

     ^

C:\Users\tanma\OneDrive\Documents\Arduino\libraries\Adafruit-ST7735-Library-master\Adafruit_ST7735.cpp:340:5: error: 'dataport' was not declared in this scope

     dataport    = portOutputRegister(digitalPinToPort(_sid));

     ^

C:\Users\tanma\OneDrive\Documents\Arduino\libraries\Adafruit-ST7735-Library-master\Adafruit_ST7735.cpp:341:5: error: 'clkpinmask' was not declared in this scope

     clkpinmask  = digitalPinToBitMask(_sclk);

     ^

C:\Users\tanma\OneDrive\Documents\Arduino\libraries\Adafruit-ST7735-Library-master\Adafruit_ST7735.cpp:342:5: error: 'datapinmask' was not declared in this scope

     datapinmask = digitalPinToBitMask(_sid);

     ^

C:\Users\tanma\OneDrive\Documents\Arduino\libraries\Adafruit-ST7735-Library-master\Adafruit_ST7735.cpp:349:7: error: '_rst' was not declared in this scope

   if (_rst) {

       ^

C:\Users\tanma\OneDrive\Documents\Arduino\libraries\Adafruit-ST7735-Library-master\Adafruit_ST7735.cpp: In member function 'void Adafruit_ST7735::initR(uint8_t)':

C:\Users\tanma\OneDrive\Documents\Arduino\libraries\Adafruit-ST7735-Library-master\Adafruit_ST7735.cpp:374:5: error: 'colstart' was not declared in this scope

     colstart = 2;

     ^

C:\Users\tanma\OneDrive\Documents\Arduino\libraries\Adafruit-ST7735-Library-master\Adafruit_ST7735.cpp:375:5: error: 'rowstart' was not declared in this scope

     rowstart = 1;

     ^

C:\Users\tanma\OneDrive\Documents\Arduino\libraries\Adafruit-ST7735-Library-master\Adafruit_ST7735.cpp:379:5: error: 'colstart' was not declared in this scope

     colstart = 2;

     ^

C:\Users\tanma\OneDrive\Documents\Arduino\libraries\Adafruit-ST7735-Library-master\Adafruit_ST7735.cpp:380:5: error: 'rowstart' was not declared in this scope

     rowstart = 3;

     ^

C:\Users\tanma\OneDrive\Documents\Arduino\libraries\Adafruit-ST7735-Library-master\Adafruit_ST7735.cpp: In member function 'void Adafruit_ST7735::setAddrWindow(uint8_t, uint8_t, uint8_t, uint8_t)':

C:\Users\tanma\OneDrive\Documents\Arduino\libraries\Adafruit-ST7735-Library-master\Adafruit_ST7735.cpp:402:16: error: 'colstart' was not declared in this scope

   writedata(x0+colstart);     // XSTART 

                ^

C:\Users\tanma\OneDrive\Documents\Arduino\libraries\Adafruit-ST7735-Library-master\Adafruit_ST7735.cpp:408:16: error: 'rowstart' was not declared in this scope

   writedata(y0+rowstart);     // YSTART

                ^

C:\Users\tanma\OneDrive\Documents\Arduino\libraries\Adafruit-ST7735-Library-master\Adafruit_ST7735.cpp: In member function 'void Adafruit_ST7735::pushColor(uint16_t)':

C:\Users\tanma\OneDrive\Documents\Arduino\libraries\Adafruit-ST7735-Library-master\Adafruit_ST7735.cpp:420:4: error: 'rsport' was not declared in this scope

   *rsport |=  rspinmask;

    ^

C:\Users\tanma\OneDrive\Documents\Arduino\libraries\Adafruit-ST7735-Library-master\Adafruit_ST7735.cpp:420:15: error: 'rspinmask' was not declared in this scope

   *rsport |=  rspinmask;

               ^

C:\Users\tanma\OneDrive\Documents\Arduino\libraries\Adafruit-ST7735-Library-master\Adafruit_ST7735.cpp:421:4: error: 'csport' was not declared in this scope

   *csport &= ~cspinmask;

    ^

C:\Users\tanma\OneDrive\Documents\Arduino\libraries\Adafruit-ST7735-Library-master\Adafruit_ST7735.cpp:421:15: error: 'cspinmask' was not declared in this scope

   *csport &= ~cspinmask;

               ^

C:\Users\tanma\OneDrive\Documents\Arduino\libraries\Adafruit-ST7735-Library-master\Adafruit_ST7735.cpp: In member function 'virtual void Adafruit_ST7735::drawPixel(int16_t, int16_t, uint16_t)':

C:\Users\tanma\OneDrive\Documents\Arduino\libraries\Adafruit-ST7735-Library-master\Adafruit_ST7735.cpp:441:4: error: 'rsport' was not declared in this scope

   *rsport |=  rspinmask;

    ^

C:\Users\tanma\OneDrive\Documents\Arduino\libraries\Adafruit-ST7735-Library-master\Adafruit_ST7735.cpp:441:15: error: 'rspinmask' was not declared in this scope

   *rsport |=  rspinmask;

               ^

C:\Users\tanma\OneDrive\Documents\Arduino\libraries\Adafruit-ST7735-Library-master\Adafruit_ST7735.cpp:442:4: error: 'csport' was not declared in this scope

   *csport &= ~cspinmask;

    ^

C:\Users\tanma\OneDrive\Documents\Arduino\libraries\Adafruit-ST7735-Library-master\Adafruit_ST7735.cpp:442:15: error: 'cspinmask' was not declared in this scope

   *csport &= ~cspinmask;

               ^

C:\Users\tanma\OneDrive\Documents\Arduino\libraries\Adafruit-ST7735-Library-master\Adafruit_ST7735.cpp: In member function 'virtual void Adafruit_ST7735::drawFastVLine(int16_t, int16_t, int16_t, uint16_t)':

C:\Users\tanma\OneDrive\Documents\Arduino\libraries\Adafruit-ST7735-Library-master\Adafruit_ST7735.cpp:467:4: error: 'rsport' was not declared in this scope

   *rsport |=  rspinmask;

    ^

C:\Users\tanma\OneDrive\Documents\Arduino\libraries\Adafruit-ST7735-Library-master\Adafruit_ST7735.cpp:467:15: error: 'rspinmask' was not declared in this scope

   *rsport |=  rspinmask;

               ^

C:\Users\tanma\OneDrive\Documents\Arduino\libraries\Adafruit-ST7735-Library-master\Adafruit_ST7735.cpp:468:4: error: 'csport' was not declared in this scope

   *csport &= ~cspinmask;

    ^

C:\Users\tanma\OneDrive\Documents\Arduino\libraries\Adafruit-ST7735-Library-master\Adafruit_ST7735.cpp:468:15: error: 'cspinmask' was not declared in this scope

   *csport &= ~cspinmask;

               ^

C:\Users\tanma\OneDrive\Documents\Arduino\libraries\Adafruit-ST7735-Library-master\Adafruit_ST7735.cpp: In member function 'virtual void Adafruit_ST7735::drawFastHLine(int16_t, int16_t, int16_t, uint16_t)':

C:\Users\tanma\OneDrive\Documents\Arduino\libraries\Adafruit-ST7735-Library-master\Adafruit_ST7735.cpp:493:4: error: 'rsport' was not declared in this scope

   *rsport |=  rspinmask;

    ^

C:\Users\tanma\OneDrive\Documents\Arduino\libraries\Adafruit-ST7735-Library-master\Adafruit_ST7735.cpp:493:15: error: 'rspinmask' was not declared in this scope

   *rsport |=  rspinmask;

               ^

C:\Users\tanma\OneDrive\Documents\Arduino\libraries\Adafruit-ST7735-Library-master\Adafruit_ST7735.cpp:494:4: error: 'csport' was not declared in this scope

   *csport &= ~cspinmask;

    ^

C:\Users\tanma\OneDrive\Documents\Arduino\libraries\Adafruit-ST7735-Library-master\Adafruit_ST7735.cpp:494:15: error: 'cspinmask' was not declared in this scope

   *csport &= ~cspinmask;

               ^

C:\Users\tanma\OneDrive\Documents\Arduino\libraries\Adafruit-ST7735-Library-master\Adafruit_ST7735.cpp: In member function 'virtual void Adafruit_ST7735::fillRect(int16_t, int16_t, int16_t, int16_t, uint16_t)':

C:\Users\tanma\OneDrive\Documents\Arduino\libraries\Adafruit-ST7735-Library-master\Adafruit_ST7735.cpp:529:4: error: 'rsport' was not declared in this scope

   *rsport |=  rspinmask;

    ^

C:\Users\tanma\OneDrive\Documents\Arduino\libraries\Adafruit-ST7735-Library-master\Adafruit_ST7735.cpp:529:15: error: 'rspinmask' was not declared in this scope

   *rsport |=  rspinmask;

               ^

C:\Users\tanma\OneDrive\Documents\Arduino\libraries\Adafruit-ST7735-Library-master\Adafruit_ST7735.cpp:530:4: error: 'csport' was not declared in this scope

   *csport &= ~cspinmask;

    ^

C:\Users\tanma\OneDrive\Documents\Arduino\libraries\Adafruit-ST7735-Library-master\Adafruit_ST7735.cpp:530:15: error: 'cspinmask' was not declared in this scope

   *csport &= ~cspinmask;

               ^

Multiple libraries were found for "Adafruit_GFX.h"
 Used: C:\Program Files (x86)\Arduino\libraries\Adafruit_GFX
 Not used: C:\Users\tanma\OneDrive\Documents\Arduino\libraries\Adafruit-GFX-Library-master
exit status 1
Error compiling for board Arduino/Genuino 101.

This report would have more information with
"Show verbose output during compilation"
option enabled in File -> Preferences.

**Comment by pljakobs** [comment]
```
Used: C:\Program Files (x86)\Arduino\libraries\Adafruit_GFX
Not used: C:\Users\tanma\OneDrive\Documents\Arduino\libraries\Adafruit-GFX-Library-master
```
this tells you your IDE is not in fact using the gihub version of Adafruit_GFX - you may want to check what version you have installed

you can include the lib you want by providing the full path.

The errors you're getting further up may or may not follow from that.

It seems highly unlikely that this is a bug in Adafruit_GFX so you'd probably be best off asking that question on the more user-focussed [adafruit forums](https://forums.adafruit.com/index.php)

pj

**Comment by microbuilder** [comment]
As mentioned above, please raise this on the Adafruit support forums. It isn't a library issue. Support happens there, github is only for pull requests and bugs with the library. Thanks!
